displayName=ImmersiveSoundNotifications
author=TrevorMDev
description=Adds sound effects for specific events
tags=sound,sounds,effect,notification,immersive,immersion
version=1
plugins=com.immersive.sound.notifications.ImmersiveSoundNotificationsPlugin
build=standard