displayName=ImmersiveSoundNotifications
author=Nobody
description=Adds sound queues for specific events
tags=
version=
plugins=com.immersive.sound.notifications.ImmersiveSoundNotificationsPlugin
build=standard